Swagger: "2.0"
info:
  title: API Evangelist News
  description: These are the items I have curated as part of this research.
  version: 1.0.0
host: definitions.apievangelist.com
basePath: /apis
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /news/:
    get:
      summary: Get News
      description: Returns all the news items.
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/news'
      tags:
        - Curated
definitions:
  news:
    properties:
      curated_id:
        description: The uniqud id for the curated item.
        type: string
      item_date:
        description: The data the item was curated.
        type: string
      title:
        description: The title for the curated item.
        type: string
      url:
        description: A URL for the curated item.
        type: string
      domain:
        description: The domain for the curated item.
        type: string
      image:
        description: An image or screenshot for the curated item.
        type: string
